org: reflexer
app: rai-discord-rr-bot
service: rai-discord-rr-bot

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-west-2'
  environment:
    DISCORD_WEBHOOK: ${param:DISCORD_WEBHOOK}

plugins:
  - serverless-webpack

functions:
  discordUpdate:
    handler: index.discordUpdate
    timeout: 240
    events:
      - schedule: rate(240 minutes)

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true