org: reflexer
app: rai-stats-bot
service: rai-stats-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-west-2'
  layers:
    # Google Chrome for AWS Lambda as a layer
    # https://github.com/shelfio/chrome-aws-lambda-layer
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:10
  environment:
    TYPE: "Hello world!"
    CONSUMER_KEY: ${param:CONSUMER_KEY}
    CONSUMER_SECRET: ${param:CONSUMER_SECRET}
    ACCESS_TOKEN: ${param:ACCESS_TOKEN}
    ACCESS_TOKEN_SECRET: ${param:ACCESS_TOKEN_SECRET}

plugins:
  - serverless-plugin-typescript
  # - serverless-plugin-chrome

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  tweetUpdate:
    handler: index.tweetUpdate
    timeout: 240
    events:
      - schedule: rate(5 minutes)
