org: reflexer
app: rai-discord-rr-bot
service: rai-discord-rr-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-west-2'
  environment:
    DISCORD_WEBHOOK: ${param:DISCORD_WEBHOOK}

plugins:
  - serverless-plugin-typescript

functions:
  discordUpdate:
    handler: index.discordUpdate
    timeout: 240
    events:
      - schedule: rate(60 minutes)
